### ISSUE TITLE
Disable redirect for aws links

### ISSUE THREAD

**Issue by plughie** [iacas/safarismile#2]
The plugin will redirect aws.amazon.com to smile.amazon.com, making it impossible to log in.

**Comment by ZevEisenberg** [comment]
It doesn't do that for me when I go to aws.amazon.com. Does it only happen for some sub-URL, perhaps?

**Comment by plughie** [comment]
It does this on the 2-factor authentication page. https://www.amazon.com/ap/signin/*

**Comment by ZevEisenberg** [comment]
Guessing you could add that URL to this line:

https://github.com/iacas/safarismile/blob/master/Smile.safariextension/smile.html#L11

Would you mind seeing if that works for you, and if it does, submitting a pull request?

**Comment by iacas** [comment]
I added the URL and am marking this as closed if that's okay.
